# Generated by Django 4.0.6 on 2022-10-03 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AdventureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('difficultyclass', models.IntegerField(blank=True, null=True)),
                ('roll', models.IntegerField()),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.adventure')),
                ('characterprogression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.characterprogression')),
                ('skillname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.skill')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
    ]
