# Generated by Django 4.0.6 on 2022-10-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adventurelog',
            old_name='skillname',
            new_name='skill',
        ),
        migrations.AddField(
            model_name='adventurelog',
            name='success',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
